language: node_js
node_js:
  - "4.2.1"
env:
  - NODE_ENV:test
after_success: 
  - "npm install coveralls@2.11.4 && cat ./client/__coverage__/phantomjs/lcov.info | ./node_modules/coveralls/bin/coveralls.js"